# Generated by Django 5.1.1 on 2024-10-30 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='password',
            field=models.CharField(default=' ', max_length=128),
        ),
        migrations.AddField(
            model_name='profesor',
            name='password',
            field=models.CharField(default=' ', max_length=128),
        ),
    ]
