# Generated by Django 5.1.2 on 2024-10-31 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_estudiante_password_profesor_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='materiasMatriculadas',
            field=models.ManyToManyField(null=True, to='api.materia'),
        ),
    ]
