# Generated by Django 5.1.2 on 2024-10-31 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_estudiante_materiasmatriculadas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estudiante',
            name='materiasMatriculadas',
        ),
    ]
