# Generated by Django 5.1.2 on 2024-10-31 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_estudiante_materiasmatriculadas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estudiante',
            name='carrera',
        ),
    ]
