# Generated by Django 5.1.1 on 2024-10-09 21:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_materia_remove_profesor_materias_profesor_materias"),
    ]

    operations = [
        migrations.CreateModel(
            name="Carrera",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("codigo", models.CharField(max_length=20)),
                ("semestres", models.IntegerField()),
                ("modalidad", models.IntegerField()),
                ("tipoCarrera", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Departamento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Horario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("horaInicio", models.TimeField()),
                ("horaFin", models.TimeField()),
                ("dia", models.IntegerField()),
                ("aula", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Pensum",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="profesor",
            name="materias",
        ),
        migrations.AddField(
            model_name="estudiante",
            name="materiasMatriculadas",
            field=models.ManyToManyField(
                blank=True, related_name="estudiantes_matriculados", to="api.materia"
            ),
        ),
        migrations.AddField(
            model_name="materia",
            name="requisito",
            field=models.ManyToManyField(
                blank=True, related_name="materias_requisito", to="api.materia"
            ),
        ),
        migrations.AddField(
            model_name="estudiante",
            name="carrera",
            field=models.ManyToManyField(to="api.carrera"),
        ),
        migrations.AddField(
            model_name="carrera",
            name="departamento",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="carreras",
                to="api.departamento",
            ),
        ),
        migrations.CreateModel(
            name="Grupo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo", models.CharField(max_length=20)),
                (
                    "materia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grupos",
                        to="api.materia",
                    ),
                ),
                (
                    "profesores",
                    models.ManyToManyField(related_name="grupos", to="api.profesor"),
                ),
                (
                    "horario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grupos",
                        to="api.horario",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Nota",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("primera", models.FloatField()),
                ("segunda", models.FloatField()),
                ("tercera", models.FloatField()),
                ("cuarta", models.FloatField()),
                (
                    "estudiante",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notas",
                        to="api.estudiante",
                    ),
                ),
                (
                    "materia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notas",
                        to="api.materia",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="carrera",
            name="pensum",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="carreras",
                to="api.pensum",
            ),
        ),
        migrations.CreateModel(
            name="Semestre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numeroSemestre", models.IntegerField()),
                (
                    "materias",
                    models.ManyToManyField(
                        related_name="semestres", to="api.materia"
                    ),
                ),
                (
                    "pensum",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="semestres",
                        to="api.pensum",
                    ),
                ),
            ],
        ),
    ]
