# Generated by Django 5.1.1 on 2024-10-09 22:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_carrera_departamento_remove_carrera_pensum'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrera',
            name='departamento',
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='carreras',
                to='api.departamento',
            ),
        ),
        migrations.AddField(
            model_name='carrera',
            name='pensum',
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='carreras',
                to='api.pensum',
            ),
        ),
    ]
