# Generated by Django 5.1.2 on 2024-11-07 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_estudiante_image_profesor_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='image',
            field=models.CharField(
                default='https://loremflickr.com/400/400', max_length=255, null=True
            ),
        ),
        migrations.AlterField(
            model_name='profesor',
            name='image',
            field=models.CharField(
                default='https://loremflickr.com/400/400', max_length=255, null=True
            ),
        ),
    ]
