# Generated by Django 5.1.1 on 2024-10-10 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_carrera_departamento_carrera_pensum'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrera',
            name='departamento',
        ),
        migrations.RemoveField(
            model_name='carrera',
            name='pensum',
        ),
        migrations.RemoveField(
            model_name='estudiante',
            name='carrera',
        ),
        migrations.RemoveField(
            model_name='grupo',
            name='horario',
        ),
        migrations.RemoveField(
            model_name='grupo',
            name='materia',
        ),
        migrations.RemoveField(
            model_name='grupo',
            name='profesores',
        ),
        migrations.RemoveField(
            model_name='materia',
            name='requisito',
        ),
        migrations.RemoveField(
            model_name='estudiante',
            name='materiasMatriculadas',
        ),
        migrations.RemoveField(
            model_name='nota',
            name='materia',
        ),
        migrations.RemoveField(
            model_name='semestre',
            name='materias',
        ),
        migrations.RemoveField(
            model_name='nota',
            name='estudiante',
        ),
        migrations.RemoveField(
            model_name='semestre',
            name='pensum',
        ),
        migrations.DeleteModel(
            name='Departamento',
        ),
        migrations.DeleteModel(
            name='Carrera',
        ),
        migrations.DeleteModel(
            name='Horario',
        ),
        migrations.DeleteModel(
            name='Grupo',
        ),
        migrations.DeleteModel(
            name='Profesor',
        ),
        migrations.DeleteModel(
            name='Materia',
        ),
        migrations.DeleteModel(
            name='Nota',
        ),
        migrations.DeleteModel(
            name='Pensum',
        ),
        migrations.DeleteModel(
            name='Semestre',
        ),
    ]
