# Generated by Django 5.1.2 on 2024-11-07 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_estudiante_image_remove_profesor_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='image',
            field=models.CharField(
                default='https://loremflickr.com/400/400', max_length=255
            ),
        ),
        migrations.AddField(
            model_name='profesor',
            name='image',
            field=models.CharField(
                default='https://loremflickr.com/400/400', max_length=255
            ),
        ),
    ]
