# Generated by Django 5.1.2 on 2024-11-12 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_estudiante_is_active_estudiante_is_staff_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='horario',
            options={
                'ordering': ['dia', 'horaInicio'],
                'verbose_name': 'Horario',
                'verbose_name_plural': 'Horarios',
            },
        ),
        migrations.AddField(
            model_name='estudiante',
            name='materiasMatriculadas',
            field=models.ManyToManyField(
                blank=True, related_name='estudiantes_matriculados', to='api.materia'
            ),
        ),
        migrations.AddField(
            model_name='horario',
            name='grupo',
            field=models.CharField(default='hola', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='horario',
            name='materia',
            field=models.CharField(default='hola', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='horario',
            name='aula',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='horarios',
                to='api.aula',
            ),
        ),
        migrations.AlterField(
            model_name='horario',
            name='dia',
            field=models.IntegerField(
                choices=[
                    (1, 'Lunes'),
                    (2, 'Martes'),
                    (3, 'Miércoles'),
                    (4, 'Jueves'),
                    (5, 'Viernes'),
                    (6, 'Sábado'),
                    (7, 'Domingo'),
                ]
            ),
        ),
        migrations.AlterUniqueTogether(
            name='horario',
            unique_together={('materia', 'grupo', 'horaInicio', 'aula')},
        ),
    ]
