# Generated by Django 5.1.2 on 2024-11-15 20:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_horario_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horario',
            name='materia',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='horarios',
                to='api.materia',
            ),
        ),
    ]
