# Generated by Django 5.1.2 on 2024-11-16 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_horario_options_alter_horario_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='celular',
            field=models.CharField(default=123, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profesor',
            name='celular',
            field=models.CharField(default=123, max_length=20),
            preserve_default=False,
        ),
    ]
