# Generated by Django 5.1.2 on 2024-11-18 20:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_estudiante_celular_profesor_celular'),
    ]

    operations = [
        migrations.CreateModel(
            name='Foro',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('titulo', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                (
                    'materia',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='foro',
                        to='api.materia',
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='Publicacion',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('titulo', models.CharField(max_length=255)),
                ('contenido', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                (
                    'estudiante',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='publicaciones',
                        to='api.estudiante',
                    ),
                ),
                (
                    'foro',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='publicaciones',
                        to='api.foro',
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('contenido', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                (
                    'estudiante',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='comentarios',
                        to='api.estudiante',
                    ),
                ),
                (
                    'publicacion',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='comentarios',
                        to='api.publicacion',
                    ),
                ),
            ],
        ),
    ]
