# Generated by Django 5.1.2 on 2024-11-26 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_foro_publicacion_comentario'),
    ]

    operations = [
        migrations.CreateModel(
            name='HorarioAsesoria',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'dia',
                    models.CharField(
                        choices=[
                            ('lunes', 'Lunes'),
                            ('martes', 'Martes'),
                            ('miercoles', 'Miércoles'),
                            ('jueves', 'Jueves'),
                            ('viernes', 'Viernes'),
                            ('sabado', 'Sábado'),
                            ('domingo', 'Domingo'),
                        ],
                        max_length=10,
                    ),
                ),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('lugar', models.CharField(max_length=255)),
                (
                    'materia',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='horarios_asesoria',
                        to='api.materia',
                    ),
                ),
            ],
        ),
    ]
