# Generated by Django 5.1.2 on 2024-11-27 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_horarioasesoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('titulo', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True, null=True)),
                (
                    'tipo',
                    models.CharField(
                        choices=[
                            ('examen', 'Examen'),
                            ('inicio_clases', 'Inicio de Clases'),
                            ('fin_clases', 'Fin de Clases'),
                            ('feriado', 'Feriado'),
                            ('otro', 'Otro'),
                        ],
                        default='otro',
                        max_length=50,
                    ),
                ),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField()),
            ],
        ),
    ]
