# Generated by Django 5.1.1 on 2024-10-09 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_carrera_departamento_horario_pensum_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrera',
            name='departamento',
        ),
        migrations.RemoveField(
            model_name='carrera',
            name='pensum',
        ),
    ]
