# Generated by Django 5.1.1 on 2024-10-10 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_remove_carrera_departamento_remove_carrera_pensum_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrera',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('nombre', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=20)),
                ('semestres', models.IntegerField()),
                ('modalidad', models.IntegerField()),
                ('tipoCarrera', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('horaInicio', models.TimeField()),
                ('horaFin', models.TimeField()),
                ('dia', models.IntegerField()),
                ('aula', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Pensum',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('nombre', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=100)),
                ('fechaNacimiento', models.DateField()),
                ('direccion', models.CharField(max_length=255)),
                ('telefono', models.CharField(max_length=100)),
                ('correoElectronico', models.CharField(max_length=100)),
                ('correoInstitucional', models.CharField(max_length=100)),
                ('fechaIngreso', models.DateField()),
                ('numeroDocumento', models.CharField(max_length=32)),
                ('tipoDocumento', models.CharField(max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='estudiante',
            name='carrera',
            field=models.ManyToManyField(to='myapp.carrera'),
        ),
        migrations.AddField(
            model_name='carrera',
            name='departamento',
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='carreras',
                to='myapp.departamento',
            ),
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('nombre', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=20)),
                ('creditos', models.IntegerField()),
                ('intensidadHoraria', models.IntegerField()),
                (
                    'requisito',
                    models.ManyToManyField(
                        blank=True,
                        related_name='materias_requisito',
                        to='myapp.materia',
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name='estudiante',
            name='materiasMatriculadas',
            field=models.ManyToManyField(
                blank=True, related_name='estudiantes_matriculados', to='myapp.materia'
            ),
        ),
        migrations.CreateModel(
            name='Nota',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('primera', models.FloatField()),
                ('segunda', models.FloatField()),
                ('tercera', models.FloatField()),
                ('cuarta', models.FloatField()),
                (
                    'estudiante',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='notas',
                        to='myapp.estudiante',
                    ),
                ),
                (
                    'materia',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='notas',
                        to='myapp.materia',
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name='carrera',
            name='pensum',
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='carreras',
                to='myapp.pensum',
            ),
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('codigo', models.CharField(max_length=20)),
                (
                    'horario',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='grupos',
                        to='myapp.horario',
                    ),
                ),
                (
                    'materia',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='grupos',
                        to='myapp.materia',
                    ),
                ),
                (
                    'profesores',
                    models.ManyToManyField(related_name='grupos', to='myapp.profesor'),
                ),
            ],
        ),
        migrations.CreateModel(
            name='Semestre',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('numeroSemestre', models.IntegerField()),
                (
                    'materias',
                    models.ManyToManyField(
                        related_name='semestres', to='myapp.materia'
                    ),
                ),
                (
                    'pensum',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='semestres',
                        to='myapp.pensum',
                    ),
                ),
            ],
        ),
    ]
