# Generated by Django 5.1.1 on 2024-10-10 20:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_carrera_departamento_horario_pensum_profesor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('nombre', models.CharField(max_length=50)),
                ('abreviacion', models.CharField(max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='estudiante',
            name='materiasMatriculadas',
        ),
        migrations.RemoveField(
            model_name='estudiante',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='profesor',
            name='nombre',
        ),
        migrations.AddField(
            model_name='estudiante',
            name='apellidos',
            field=models.CharField(default=' ', max_length=50),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='nombres',
            field=models.CharField(default=' ', max_length=50),
        ),
        migrations.AddField(
            model_name='pensum',
            name='nombre',
            field=models.CharField(default=' ', max_length=100),
        ),
        migrations.AddField(
            model_name='profesor',
            name='apellidos',
            field=models.CharField(default=' ', max_length=50),
        ),
        migrations.AddField(
            model_name='profesor',
            name='nombres',
            field=models.CharField(default=' ', max_length=50),
        ),
        migrations.AlterField(
            model_name='carrera',
            name='departamento',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='carreras',
                to='myapp.departamento',
            ),
        ),
        migrations.AlterField(
            model_name='carrera',
            name='pensum',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='carreras',
                to='myapp.pensum',
            ),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='codigo',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='correoElectronico',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='correoInstitucional',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='numeroDocumento',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='telefono',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='profesor',
            name='codigo',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='profesor',
            name='correoElectronico',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='profesor',
            name='correoInstitucional',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='profesor',
            name='numeroDocumento',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='profesor',
            name='telefono',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='tipoDocumento',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to='myapp.tipodocumento',
            ),
        ),
        migrations.AlterField(
            model_name='profesor',
            name='tipoDocumento',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to='myapp.tipodocumento',
            ),
        ),
    ]
