# Generated by Django 5.1.1 on 2024-10-10 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_tipodocumento_remove_estudiante_materiasmatriculadas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='materiasMatriculadas',
            field=models.ManyToManyField(
                null=True, related_name='estudiantes_matriculados', to='myapp.materia'
            ),
        ),
    ]
